# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-25 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4'),
        ),
    ]
